monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - app
        - address
        - file
        - email

    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [ 404, 405 ]
            buffer_size: 100 # How many messages should be saved? Prevent memory leaks
            channels: [ '!app', '!event', '!email', '!address', '!file' ]
        console:
            type: console
            process_psr_3_messages: false
            channels: [ "!event", "!doctrine" ]
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            max_files: 10
            channels: [ "app", 'email', 'address', 'file' ]
when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                buffer_size: 100 # How many messages should be saved? Prevent memory leaks
                channels: [ '!app', '!event', '!address', '!email', '!file' ]
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine" ]
            nested:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: info
                max_files: 10
                channels: [ "app", 'address', 'email', 'file' ]
